### PR TITLE
Have the example code actually return the things you think it would

### PR DESCRIPTION
**Pull request by bmchrist**
See https://github.com/strydercorp/handshake/pull/4399#discussion_r64497092

### CODE REVIEW

**Comment by bmchrist** [comment]
Previously someone (such as myself) might accidentally swap out one of the 'true' lines in the case statement with a check, but forget to add return, which means it would fall back to the final line's true.

This doesn't change the default logic but makes it much more clear/explicit

**Comment by sgringwe** [comment]
@bmchrist you actually fixed this in 2 ways. by removing the `true` at the end, the `case` statement would have been the implied return of the method. you also fixed it by doing an explicit return.

**Comment by sgringwe** [comment]
lgtm

**Comment by bmchrist** [comment]
TWO FOR ONE WOO

**Pull request merged**
